### ISSUE TITLE
Unit deployment from base

### ISSUE THREAD

**Issue by Kuczek8** [wynn-rj/sword-and-bored-game#241]
Units on the map can be redeployed from the Player Base to a town. This will move the unit back into the town, but leave the squad object on the map wherever they were at,

Steps to replicate:
- Deploy unit(s) from Player base to town
- Deploy squad from town
- Go back into Player base and redeploy the same unit(s) to the town
- Go to the town and deploy squad
- Now there are two squads on the map

**Comment by cthomas68** [comment]
I plan on fixing this. Thanks for bringing it back to my attention!
